version: "3.9"
services:
  scraper_main:
   image: "scraper_main:latest"
   links:
     - redis
  scraper_tomongo:
   image: "scraper_tomongo:latest"
   links:
     - redis
     - mongo
  redis:
   image: "redis:latest"
   ports:
    - "6379:6379"
  mongo:
   image: "mongo:latest"
   ports:
    - "8001:27017"